name: Release test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: 27 18 * * 4 # weekly, 18:27 on Thursday

# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners

env:
  ORG_GRADLE_PROJECT_checksumIgnore: true

jobs:
  release-avatica:
    strategy:
      fail-fast: false
      matrix:
        gradle-version: [wrapper, rc, nightly]
    name: 'Calcite Avatica ${{ matrix.gradle-version }}'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50
        submodules: true
    - name: 'Set up JDK 11'
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: 'Start release environment'
      run: |
        gpg --import .github/workflows/test-key.asc
        git clone --depth 100 https://github.com/vlsi/asflike-release-environment.git ../asflike-release-environment
        cd ../asflike-release-environment
        cp .env_calcite-avatica .env
        docker-compose build vcs
        docker-compose up -d
    - name: 'Clone Calcite Avatica'
      run: |
        git clone --depth 100 https://github.com/apache/calcite-avatica.git ../calcite-avatica
        git rev-parse HEAD
    - name: 'Prepare Candidate'
      uses: burrunan/gradle-cache-action@v1
      with:
        job-id: avatica
        gradle-version: ${{ matrix.gradle-version }}
        build-root-directory: ../calcite-avatica
        arguments: -Pnoverify --no-parallel --no-daemon prepareVote -Prc=1 -PlocalReleasePlugins -PasfTestNexusUsername=test -PasfTestNexusPassword=test -PasfTestGitSourceUsername=test -PasfTestGitSourcePassword=test -PasfTestSvnUsername=test -PasfTestSvnPassword=test -Psigning.gnupg.keyName=289023DE2663BD17 -PuseGpgCmd -Psigning.gnupg.useLegacyGpg=true
    - name: 'Publish Release'
      uses: burrunan/gradle-cache-action@v1
      with:
        job-id: avatica
        gradle-version: ${{ matrix.gradle-version }}
        build-root-directory: ../calcite-avatica
        arguments: -Pnoverify --no-parallel --no-daemon publishDist -Prc=1 -PlocalReleasePlugins -PasfTestNexusUsername=test -PasfTestNexusPassword=test -PasfTestGitSourceUsername=test -PasfTestGitSourcePassword=test -PasfTestSvnUsername=test -PasfTestSvnPassword=test

  release-calcite:
    strategy:
      fail-fast: false
      matrix:
        gradle-version: [wrapper, rc, nightly]
    name: 'Calcite ${{ matrix.gradle-version }}'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50
        submodules: true
    - name: 'Set up JDK 11'
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: 'Start release environment'
      run: |
        gpg --import .github/workflows/test-key.asc
        git clone --depth 100 https://github.com/vlsi/asflike-release-environment.git ../asflike-release-environment
        cd ../asflike-release-environment
        cp .env_calcite .env
        docker-compose build vcs
        docker-compose up -d
    - name: 'Clone Calcite'
      run: |
        git clone --depth 100 https://github.com/apache/calcite.git ../calcite
        git rev-parse HEAD
    - name: 'Prepare Candidate'
      uses: burrunan/gradle-cache-action@v1
      with:
        job-id: calcite
        gradle-version: ${{ matrix.gradle-version }}
        build-root-directory: ../calcite
        arguments: -Pnoverify -PskipSigning --no-parallel --no-daemon prepareVote -Prc=1 -PlocalReleasePlugins -PasfTestNexusUsername=test -PasfTestNexusPassword=test -PasfTestGitSourceUsername=test -PasfTestGitSourcePassword=test -PasfTestSvnUsername=test -PasfTestSvnPassword=test -Psigning.gnupg.keyName=289023DE2663BD17 -PuseGpgCmd -Psigning.gnupg.useLegacyGpg=true
    - name: 'Publish Release'
      uses: burrunan/gradle-cache-action@v1
      with:
        job-id: calcite
        execution-only-caches: true
        gradle-version: ${{ matrix.gradle-version }}
        build-root-directory: ../calcite
        arguments: -Pnoverify --no-parallel --no-daemon publishDist -Prc=1 -PlocalReleasePlugins -PasfTestNexusUsername=test -PasfTestNexusPassword=test -PasfTestGitSourceUsername=test -PasfTestGitSourcePassword=test -PasfTestSvnUsername=test -PasfTestSvnPassword=test

  release-jmeter:
    strategy:
      fail-fast: false
      matrix:
        gradle-version: [wrapper, rc, nightly]
    name: 'JMeter ${{ matrix.gradle-version }}'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50
        submodules: true
    - name: 'Set up JDK 11'
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: 'Start release environment'
      run: |
        gpg --import .github/workflows/test-key.asc
        git clone --depth 100 https://github.com/vlsi/asflike-release-environment.git ../asflike-release-environment
        cd ../asflike-release-environment
        cp .env_jmeter .env
        docker-compose build vcs
        docker-compose up -d
    - name: 'Clone JMeter'
      run: |
        git clone --depth 100 https://github.com/apache/jmeter.git ../jmeter
        git rev-parse HEAD
    - name: 'Prepare Candidate'
      uses: burrunan/gradle-cache-action@v1
      with:
        job-id: jmeter
        multi-cache-enabled: false
        gradle-version: ${{ matrix.gradle-version }}
        build-root-directory: ../jmeter
        arguments: -Pnoverify --no-parallel --no-daemon prepareVote -Prc=1 -PlocalReleasePlugins -PasfTestNexusUsername=test -PasfTestNexusPassword=test -PasfTestGitSourceUsername=test -PasfTestGitSourcePassword=test -PasfTestSvnUsername=test -PasfTestSvnPassword=test -PasfTestGitSitePreviewUsername=test -PasfTestGitSitePreviewPassword=test -Psigning.gnupg.keyName=289023DE2663BD17 -PuseGpgCmd -Psigning.gnupg.useLegacyGpg=true
    - name: 'Publish Release'
      uses: burrunan/gradle-cache-action@v1
      with:
        job-id: jmeter
        multi-cache-enabled: false
        execution-only-caches: true
        gradle-version: ${{ matrix.gradle-version }}
        build-root-directory: ../jmeter
        arguments: -Pnoverify --no-parallel --no-daemon publishDist -Prc=1 -PlocalReleasePlugins -PasfTestNexusUsername=test -PasfTestNexusPassword=test -PasfTestGitSourceUsername=test -PasfTestGitSourcePassword=test -PasfTestSvnUsername=test -PasfTestSvnPassword=test

  release-autostyle:
    strategy:
      fail-fast: false
      matrix:
        gradle-version: [wrapper, rc, nightly]
    name: 'Autostyle ${{ matrix.gradle-version }}'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50
        submodules: true
    - name: 'Set up JDK 8'
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: 'Start release environment'
      run: |
        gpg --import .github/workflows/test-key.asc
        git clone --depth 100 https://github.com/vlsi/asflike-release-environment.git ../asflike-release-environment
        cd ../asflike-release-environment
        cp .env_autostyle .env
        docker-compose build vcs
        docker-compose up -d
    - name: 'Clone Autostyle'
      run: |
        git clone --depth 100 https://github.com/autostyle/autostyle.git ../autostyle
        git rev-parse HEAD
    - name: 'Prepare Candidate'
      uses: burrunan/gradle-cache-action@v1
      with:
        job-id: autostyle
        gradle-version: ${{ matrix.gradle-version }}
        build-root-directory: ../autostyle
        arguments: -Pnoverify --no-parallel --no-daemon prepareVote -Prc=1 -PlocalReleasePlugins -PghTestNexusUsername=test -PghTestNexusPassword=test -PghTestGitSourceUsername=test -PghTestGitSourcePassword=test -Psigning.gnupg.keyName=289023DE2663BD17 -PuseGpgCmd -Psigning.gnupg.useLegacyGpg=true
    - name: 'Publish Release'
      uses: burrunan/gradle-cache-action@v1
      with:
        job-id: autostyle
        execution-only-caches: true
        gradle-version: ${{ matrix.gradle-version }}
        build-root-directory: ../autostyle
        arguments: -Pnoverify --no-parallel --no-daemon publishDist -Prc=1 -PlocalReleasePlugins -PghTestNexusUsername=test -PghTestNexusPassword=test -PghTestGitSourceUsername=test -PghTestGitSourcePassword=test

  release-pgjdbc:
    strategy:
      fail-fast: false
      matrix:
        gradle-version: [wrapper, rc, nightly]
    name: 'pgjdbc ${{ matrix.gradle-version }}'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50
        submodules: true
    - name: 'Set up JDK 8'
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: 'Start release environment'
      run: |
        gpg --import .github/workflows/test-key.asc
        git clone --depth 100 https://github.com/vlsi/asflike-release-environment.git ../asflike-release-environment
        cd ../asflike-release-environment
        cp .env_pgjdbc .env
        docker-compose build vcs
        docker-compose up -d
    - name: 'Clone pgjdbc'
      run: |
        git clone --depth 100 https://github.com/pgjdbc/pgjdbc.git ../pgjdbc
        git rev-parse HEAD
    - name: 'Prepare Candidate'
      uses: burrunan/gradle-cache-action@v1
      with:
        job-id: pgjdbc
        gradle-version: ${{ matrix.gradle-version }}
        build-root-directory: ../pgjdbc
        arguments: -Pnoverify --no-parallel --no-daemon prepareVote -Prc=1 -PlocalReleasePlugins -PghTestNexusUsername=test -PghTestNexusPassword=test -PghTestGitSourceUsername=test -PghTestGitSourcePassword=test -Psigning.gnupg.keyName=289023DE2663BD17 -PuseGpgCmd -Psigning.gnupg.useLegacyGpg=true
    - name: 'Publish Release'
      uses: burrunan/gradle-cache-action@v1
      with:
        job-id: pgjdbc
        execution-only-caches: true
        gradle-version: ${{ matrix.gradle-version }}
        build-root-directory: ../pgjdbc
        arguments: -Pnoverify --no-parallel --no-daemon publishDist -Prc=1 -PlocalReleasePlugins -PghTestNexusUsername=test -PghTestNexusPassword=test -PghTestGitSourceUsername=test -PghTestGitSourcePassword=test
